HW13 calendar
rez1dent3/otus-hw pull request #13
Opened 2022-10-16 19:23 UTC by rez1dent3

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-11-03 02:17 UTC, dshemin requested changes

2022-11-03 02:17 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
В текущем интерфейсе АПИ, клиент не сможет понять, завершилась ли его операция успешно или нет. Хорошая практика - вернуть статус обработки запроса. успешно или нет, и сообщение об ошибке.

2022-11-03 02:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/storage.go
> +type ConnInterface interface {
Немного странный интерфейс. Внутри NewConnect мы уже подключаемся, зачем нам Connect тут?

2022-11-03 02:17 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	repo, ok := selStorage.(app.Storage)
Посмотрел код метода NewConnect. Стоит поменять его сигнатуру, чтобы он возвращал app.Storage, дополнив этот интерфейс методом Close.

2022-11-03 02:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		return ErrCreateEvent
То, что у нас есть константная ошибка - это хорошо, но было бы отлично нам как-то добавить к ней контекста, чтобы иметь причину, почему мы не смогли создать событие.

2022-11-03 14:41 UTC, rez1dent3 commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
Я думаю, что вы не совсем правы. Ошибка на стороне клиента будет.
<img width="1436" alt="Снимок экрана 2022-11-03 в 17 34 45" src="https://user-images.githubusercontent.com/5111255/199749848-664d715b-cf99-4fef-9b23-39d41a64c7e6.png">

Нет смысла дублировать запрос в ответ или отправлять сообщение "данные сохранены".

В моем контракте, клиент генерирует ID события. А значит, что на стороне клиента уже есть все данные, которые могут ему понадобиться (аля гексагональная архитектура, привет CQRS). Если это когда-нибудь изменится, то можно будет создать новый контракт.

2022-11-03 14:42 UTC, rez1dent3 commented on hw12_13_14_15_calendar/internal/storage/storage.go
> +type ConnInterface interface {
Да, вы правы. Я уберу этот интерфейс

2022-11-03 14:42 UTC, rez1dent3 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	repo, ok := selStorage.(app.Storage)
Согласен, внесу правки

2022-11-03 15:17 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
Я не про копирвание запроса в ответ и сообщений что всё прошло хорошо. Я про то, что в случае REST API мы возвращаем статус код в заголовках и в тело добавляем некоторое сообщение, типа: не валидное имя. Тут же вы смотрите на то, как себя ведёт конвертация GRPC в JSON API. Сделайте прямой GRPC запрос.

2022-11-04 07:49 UTC, rez1dent3 commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
Спасибо вам за уточнение. Не могли бы вы подсказать, как можно самым простым запросом сформировать корректный запрос (если я понял, то без grpc клиента)?

---

`protoc` генерирует ClientConnInterface, который имеет метод _Invoke_(..., **reply** any, ...) **error**. Те, если rpc-метод возвращает данные, то они запишутся в reply, иначе попадут в error. Я не генерировал клиенты для других языков, но думаю ошибка там тоже будет.

```golang
// ClientConnInterface defines the functions clients need to perform unary and
// streaming RPCs.  It is implemented by *ClientConn, and is only intended to
// be referenced by generated code.
type ClientConnInterface interface {
	// Invoke performs a unary RPC and returns after the response is received
	// into reply.
	Invoke(ctx context.Context, method string, args interface{}, reply interface{}, opts ...CallOption) error
	// NewStream begins a streaming RPC.
	NewStream(ctx context.Context, desc *StreamDesc, method string, opts ...CallOption) (ClientStream, error)
}
```

Сгенерированный клиент для моего сервиса выглядит так:
```golang
type CalendarClient interface {
	CreateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteEventV1(ctx context.Context, in *EventIdV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListEventsDayV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventsWeekV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventsMonthV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
}
```

Те, все методы возвращают resp и err. Согласно контракту, error, в данном случае, нужно проверять перед работой с данными.

---

Можно, конечно, вынести Response в контракт и status через enum сделать. Вы об этом? Чтобы ошибки были согласованы на уровне proto-контракта

2022-11-04 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
Есть вот такая утилитка https://github.com/fullstorydev/grpcurl, помогает отлаживать.

По поводу интерфейса клиента. Тот error что он возвращает - это ошибка транспортного уровня, типа не могли соединится и т.п. Но там не будет ошибок прикладного уровня.

2022-11-05 09:26 UTC, rez1dent3 commented on hw12_13_14_15_calendar/api/EventService.proto
> +service Calendar {
Спасибо. Внес правки^

2022-11-05 18:20 UTC, dshemin approved these changes

2022-11-12 12:52 UTC, merged